# 게시판 프로젝트 테이블
CREATE TABLE board(
	BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(30) NOT NULL
	, WRITER VARCHAR(20) NOT NULL
	, CONTENT VARCHAR(50)
	, READ_CNT INT DEFAULT 0
	, CREATE_DATE DATETIME DEFAULT SYSDATE()
);

SELECT * FROM BOARD;

INSERT INTO BOARD (TITLE, WRITER, CONTENT, READ_CNT) 
VALUES ('안녕하세요', '김자바', '김자바입니다', 120);

INSERT INTO BOARD (TITLE, WRITER, CONTENT, READ_CNT) 
VALUES ('안녕하수꽈', '제주바', '제주바입니다', 210);
COMMIT;

#상품 정보 테이블
CREATE TABLE ITEM (
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_CATEGORY VARCHAR(30) NOT NULL
	, ITEM_NAME VARCHAR(20) NOT NULL UNIQUE
	, ITEM_PRICE INT NOT NULL
	, ITEM_INTRO VARCHAR(50)
	, ITEM_STATUS VARCHAR(10)	# 상품준비중, 판매중, 품절
	, REG_DATE DATETIME DEFAULT SYSDATE()
);
SELECT * FROM ITEM;

INSERT INTO ITEM (ITEM_CATEGORY, ITEM_NAME, ITEM_PRICE, ITEM_STATUS) 
VALUES ('상의', '반바지', 2000, '판매중');
COMMIT;

DELETE FROM ITEM WHERE ITEM_NUM = 1;
COMMIT;

INSERT INTO ITEM (ITEM_CATEGORY, ITEM_NAME, ITEM_PRICE, ITEM_STATUS) 
VALUES ('상의', '반팔티', 2000, '판매중');
INSERT INTO ITEM (ITEM_CATEGORY, ITEM_NAME, ITEM_PRICE, ITEM_STATUS) 
VALUES ('하의', '반바지', 1000, '준비중');
INSERT INTO ITEM (ITEM_CATEGORY, ITEM_NAME, ITEM_PRICE, ITEM_STATUS) 
VALUES ('액세사리', '시계', 3000, '판매중');
INSERT INTO ITEM (ITEM_CATEGORY, ITEM_NAME, ITEM_PRICE, ITEM_STATUS) 
VALUES ('상의', '롱패딩', 4000, '매진');
COMMIT;

SELECT SUM(ITEM_PRICE) FROM item;

study_db