
#도서 쇼핑몰 프로젝트 테이블

# <전체 테이블 리스트>
#1. (회원) 테이블
#2. (도서 카테고리) 테이블
#3. (도서 정보) 테이블
#4. (구매) 테이블
#5. (장바구니) 테이블

#1. (회원) 테이블
DROP TABLE shop_member;
CREATE TABLE SHOP_MEMBER(
	MEM_ID VARCHAR(20) PRIMARY KEY #아이디 (ID)
	, MEM_NAME VARCHAR(20) NOT NULL #이름
	, MEM_TEL VARCHAR(20) #전화번호 (010-1111-2222)
	, MEM_ADDR VARCHAR(50) #일반주소
	, ADDR_DETAIL VARCHAR(50) #주소(상세)
	, MEM_EMAIL VARCHAR(50) UNIQUE #이메일
	, MEM_PW VARCHAR(20) NOT NULL #비밀번호 (PW)
	, MEM_ROLE VARCHAR(10) NOT NULL DEFAULT 'USER' #관리자(ADMIN) / 사용자(USER)
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);


#2. (도서 카테고리) 테이블
CREATE TABLE BOOK_CATEGORY (
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CATE_NAME VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO BOOK_CATEGORY VALUES (1, '소설');
INSERT INTO BOOK_CATEGORY VALUES (2, '인터넷/IT');
INSERT INTO BOOK_CATEGORY VALUES (3, '자기계발');
COMMIT;

#3. (도서 정보) 테이블
CREATE TABLE book (
	BOOK_NUM	INT PRIMARY KEY AUTO_INCREMENT
	, TITLE VARCHAR(20) NOT NULL
	, PUBLISHER VARCHAR(20) NOT NULL
	, PRICE INT NOT NULL
	, REG_DATE DATETIME DEFAULT SYSDATE() #쇼핑몰에 상품 등록한 날짜
	, BOOK_INTRO VARCHAR(50)
	, CATE_NUM INT REFERENCES BOOK_CATEGORY (CATE_NUM)
);

#4. (장바구니) 테이블
DROP TABLE SHOP_CART;
CREATE TABLE SHOP_CART (
	CART_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BOOK_NUM INT REFERENCES book (BOOK_NUM) #외래키 넣기 (없는 상품 뜨는 무서운 버그 방지)
	, CART_CNT INT NOT NULL #장바구니에 담은 도서 수량
	, MEM_ID VARCHAR(20) REFERENCES shop_member (MEM_ID)
	, TOTAL_PRICE INT NOT NULL
	, CART_DATE DATETIME DEFAULT SYSDATE()
);

# 도서 이미지 정보 테이블
CREATE TABLE BOOK_IMG (
	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_IMG_NAME VARCHAR(100) # 원본 파일명
	, ATTACHED_IMG_NAME VARCHAR(100) # 첨부된 파일명
	, BOOK_NUM INT REFERENCES book (BOOK_NUM) ON DELETE CASCADE # 이미지의 원본 도서 번호
	, IS_MAIN VARCHAR(3) #메인 이미지 : 'Y' 서브 이미지 : 'N'
);

#5. 구매 정보 테이블
CREATE TABLE SHOP_BUY (
	BUY_NUM INT PRIMARY KEY AUTO_INCREMENT #책 정보
	, BOOK_NUM INT REFERENCES book (BOOK_NUM) #외래키 넣기 (없는 상품 뜨는 무서운 버그 방지)
	, MEM_ID VARCHAR(20) REFERENCES shop_member (MEM_ID) #주문자
	, BUY_DATE DATETIME DEFAULT SYSDATE() #날짜
	, BUY_CNT INT
	, ORDER_NUM INT #주문번호 한 번에 여러상품을 구매하면 동일한 주문번호를 가짐
);

# 최근 10일에 해당하는 날짜를 조회
SELECT ADDDATE(CURRENT_DATE(), -9)
	UNION ALL
	SELECT ADDDATE(CURRENT_DATE(), -8)
	UNION ALL
	SELECT ADDDATE(CURRENT_DATE(), -7)
	UNION ALL
	SELECT ADDDATE(CURRENT_DATE(), -6)
	UNION ALL
	SELECT ADDDATE(CURRENT_DATE(), -5)
	UNION ALL
	SELECT ADDDATE(CURRENT_DATE(), -4)
	UNION ALL
	SELECT ADDDATE(CURRENT_DATE(), -3)
	UNION ALL
	SELECT ADDDATE(CURRENT_DATE(), -2)
	UNION ALL
	SELECT ADDDATE(CURRENT_DATE(), -1)	
	UNION ALL
	SELECT CURRENT_DATE();
	
# 오늘의 매출
SELECT IFNULL(SUM((SELECT PRICE
			FROM book
			WHERE BOOK_NUM = shop_buy.BOOK_NUM) * BUY_CNT) , 0)
FROM shop_buy
WHERE TO_CHAR(BUY_DATE, 'YYYY-MM-DD') = CURRENT_DATE()
UNION ALL
SELECT IFNULL(SUM((SELECT PRICE
			FROM book
			WHERE BOOK_NUM = shop_buy.BOOK_NUM) * BUY_CNT) , 0)
FROM shop_buy
WHERE TO_CHAR(BUY_DATE, 'YYYY-MM-DD') = ADDDATE(CURRENT_DATE(), -1)
UNION ALL
SELECT IFNULL(SUM((SELECT PRICE
			FROM book
			WHERE BOOK_NUM = shop_buy.BOOK_NUM) * BUY_CNT) , 0)
FROM shop_buy
WHERE TO_CHAR(BUY_DATE, 'YYYY-MM-DD') = ADDDATE(CURRENT_DATE(), -2)
UNION ALL
SELECT IFNULL(SUM((SELECT PRICE
			FROM book
			WHERE BOOK_NUM = shop_buy.BOOK_NUM) * BUY_CNT) , 0)
FROM shop_buy
WHERE TO_CHAR(BUY_DATE, 'YYYY-MM-DD') = ADDDATE(CURRENT_DATE(), -3)
UNION ALL
SELECT IFNULL(SUM((SELECT PRICE
			FROM book
			WHERE BOOK_NUM = shop_buy.BOOK_NUM) * BUY_CNT) , 0)
FROM shop_buy
WHERE TO_CHAR(BUY_DATE, 'YYYY-MM-DD') = ADDDATE(CURRENT_DATE(), -4)
UNION ALL
SELECT IFNULL(SUM((SELECT PRICE
			FROM book
			WHERE BOOK_NUM = shop_buy.BOOK_NUM) * BUY_CNT) , 0)
FROM shop_buy
WHERE TO_CHAR(BUY_DATE, 'YYYY-MM-DD') = ADDDATE(CURRENT_DATE(), -5)
UNION ALL
SELECT IFNULL(SUM((SELECT PRICE
			FROM book
			WHERE BOOK_NUM = shop_buy.BOOK_NUM) * BUY_CNT) , 0)
FROM shop_buy
WHERE TO_CHAR(BUY_DATE, 'YYYY-MM-DD') = ADDDATE(CURRENT_DATE(), -6)
UNION ALL
SELECT IFNULL(SUM((SELECT PRICE
			FROM book
			WHERE BOOK_NUM = shop_buy.BOOK_NUM) * BUY_CNT) , 0)
FROM shop_buy
WHERE TO_CHAR(BUY_DATE, 'YYYY-MM-DD') = ADDDATE(CURRENT_DATE(), -7)
UNION ALL
SELECT IFNULL(SUM((SELECT PRICE
			FROM book
			WHERE BOOK_NUM = shop_buy.BOOK_NUM) * BUY_CNT) , 0)
FROM shop_buy
WHERE TO_CHAR(BUY_DATE, 'YYYY-MM-DD') = ADDDATE(CURRENT_DATE(), -8)
UNION ALL
SELECT IFNULL(SUM((SELECT PRICE
			FROM book
			WHERE BOOK_NUM = shop_buy.BOOK_NUM) * BUY_CNT) , 0)
FROM shop_buy
WHERE TO_CHAR(BUY_DATE, 'YYYY-MM-DD') = ADDDATE(CURRENT_DATE(), -9);


SELECT BUY_DATE
	, TO_CHAR(BUY_DATE, 'YYYY-MM-DD')
FROM shop_buy;

#UNION ALL
#여러 셀렉트문을 하나의 셀렉트처럼 동시 실헹 #

SELECT *
FROM shop_buy;

SELECT *
FROM shop_cart;

SELECT * 
FROM shop_member

INSERT INTO book_img (ORIGIN_IMG_NAME, ATTACHED_IMG_NAME, BOOK_NUM, IS_MAIN)
VALUES 
('abc.jpg', 'aaa-bbb.jpg', 1, 'Y'),
('abc.jpg', 'aaa-bbb.jpg', 1, 'Y'),
('abc.jpg', 'aaa-bbb.jpg', 1, 'Y');


# 다음에 들어갈 book_num을 조회 (최대 book_num + 1)
SELECT MAX(BOOK_NUM) + 1 FROM book;

SELECT IFNULL(MAX(BOOK_NUM) , 0) + 1 FROM book;

SELECT * FROM book;
SELECT * FROM book_img;
SELECT * FROM shop_buy;

DELETE FROM shop_buy
WHERE ORDER_NUM IS NULL;
COMMIT;





