
# 자동차정보(CAR_INFO)
CREATE TABLE CAR_INFO (
	MODEL_NUM INT  AUTO_INCREMENT PRIMARY KEY # 모델번호(PK)
	, MODEL_NAME VARCHAR(20) NOT NULL # 모델명
	, MODEL_PRICE INT NOT NULL # 금액
	, MADE_COMPANY VARCHAR(20) NOT NULL # 제조사
);

SELECT * 
FROM car_info;


# 자동차판매정보(SALES_INFO)
CREATE TABLE SALES_INFO (
	SELL_NUM INT  AUTO_INCREMENT PRIMARY KEY # 판매번호(PK)
	, CUS_NAME VARCHAR(20) NOT NULL #구매자명
	, CUS_PHONE VARCHAR(20) #구매자연락처
	, COLOR VARCHAR(20) NOT NULL #색상
	, SELL_DATE DATETIME DEFAULT SYSDATE() NOT NULL #판매일
	, MODEL_NUM INT NOT NULL REFERENCES CAR_INFO(MODEL_NUM)
);

SELECT * 
FROM sales_info;