CREATE TABLE BOOK(
	BOOK_NUM INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	TITLE VARCHAR(20) NOT NULL UNIQUE,
	CG VARCHAR(10) NOT NULL,
	WRITER VARCHAR(20) NOT NULL,
	PRICE INT,
	PUBLSISH_DATE DATETIME DEFAULT SYSDATE(),
	RENT_CNT INT
);

INSERT INTO BOOK (TITLE, CG, WRITER, PRICE, RENT_CNT)
VALUES ('자바 기초', 'IT/인터넷', '김자바', 10000, 10);
INSERT INTO BOOK (TITLE, CG, WRITER, PRICE, RENT_CNT)
VALUES ('일본여행기', '에세이', '윤여행', 7000, 5);
INSERT INTO BOOK (TITLE, CG, WRITER, PRICE, RENT_CNT)
VALUES ('재태크 시작하기', '자기계발', '김자바', 15000, 15);
INSERT INTO BOOK (TITLE, CG, WRITER, PRICE, RENT_CNT)
VALUES ('리액트 따라하기', 'IT/인터넷', '김자바', 20000, 3);
INSERT INTO BOOK (TITLE, CG, WRITER, PRICE, RENT_CNT)
VALUES ('직장인 월급관리', '자기계발', '윤여행', 13000, 8);

SELECT * FROM BOOK;

#2. 윤여행 저자가 쓴 도서의 가격을 1000원 인상하고, 대여횟수를 5씩 증가시키세요.
UPDATE BOOK
SET
PRICE = PRICE + 1000, 
RENT_CNT = RENT_CNT + 5
WHERE WRITER = '윤여행';
COMMIT;