#연습 (문제1) 친구정보를 관리하는 테이블을 생성
CREATE TABLE MY_FRIEND (
	FRIEND_NUM INT PRIMARY KEY,
	FRIEND_ID VARCHAR(10) NOT NULL,
	FRIEND_PW VARCHAR(10) NOT NULL,
	FRIEND_NAME VARCHAR(10) NOT NULL,
	AGE INT,
	EMAIL VARCHAR(100) UNIQUE
);
#연습 (문제2) 위에서 생성한 MY_MEMBER에 아래 표에서 
#제시하는 데이터를 삽입하는 쿼리문을 작성하세요
INSERT INTO MY_FRIEND (FRIEND_NUM, FRIEND_ID, FRIEND_PW, FRIEND_NAME, AGE, EMAIL) VALUES (1, 'KIM123', '123', '김자바', 20, '주니어네이버');
INSERT INTO MY_FRIEND (FRIEND_NUM, FRIEND_ID, FRIEND_PW, FRIEND_NAME, AGE, EMAIL) VALUES (2, 'YUN456', '456', '윤자바', 21, '네이버');
INSERT INTO MY_FRIEND (FRIEND_NUM, FRIEND_ID, FRIEND_PW, FRIEND_NAME, AGE, EMAIL) VALUES (3, 'HONG789', '789', '홍자바', 22, '올드네이버');
INSERT INTO MY_FRIEND (FRIEND_NUM, FRIEND_ID, FRIEND_PW, FRIEND_NAME, AGE, EMAIL) VALUES (4, 'PARK101112', '101112', '박자바', 23, '베리올드네이버');

DELETE FROM MY_FRIEND;

CREATE TABLE MY_FRIEND (
	FRIEND_NUM INT PRIMARY KEY,
	FRIEND_ID VARCHAR(10) NOT NULL,
	FRIEND_PW VARCHAR(10) NOT NULL,
	FRIEND_NAME VARCHAR(10) NOT NULL,
	AGE INT,
	EMAIL VARCHAR(100) UNIQUE
);

SELECT * FROM MY_FRIEND;
INSERT INTO MY_FRIEND (FRIEND_NUM, FRIEND_ID, FRIEND_PW, FRIEND_NAME, AGE, EMAIL) VALUES (1, 'KIM123', '123', '김자바', 20, 'KIM@GMAIL.COM');
INSERT INTO MY_FRIEND (FRIEND_NUM, FRIEND_ID, FRIEND_PW, FRIEND_NAME, AGE, EMAIL) VALUES (2, 'YUN456', '456', '윤자바', 21, 'YUN@GMAIL.COM');
INSERT INTO MY_FRIEND (FRIEND_NUM, FRIEND_ID, FRIEND_PW, FRIEND_NAME, AGE, EMAIL) VALUES (3, 'HONG789', '789', '홍자바', 22, 'HONG@GMAIL.COM');
INSERT INTO MY_FRIEND (FRIEND_NUM, FRIEND_ID, FRIEND_PW, FRIEND_NAME, AGE, EMAIL) VALUES (4, 'PARK101112', '101112', '박자바', 23, 'PARK@GMAIL.COM');

SELECT * FROM MY_FRIEND;

#연습 (문제3) 위에서 생성한 MY_MEMBER에서 
#회원번호가 3번인 회원의 이름을 '홍스위프트'로, 
#나이는 현재 나이에서 5를 증가시킨 값으로 수정하는 쿼리문을 작성하세요.
UPDATE MY_FRIEND
SET FRIEND_NAME = '홍스위프트', AGE = AGE + 5 WHERE FRIEND_NUM = 3;

SELECT * FROM MY_FRIEND;

#연습 (문제4-EMP)
#4.﻿﻿﻿급여가 500에서 3000 사이이고 
#커미션이 NULL이 아닌 사원의 사원번호, 사원명, 급여, 커미션을 
#조회하는 쿼리문을 작성하시오.

SELECT * FROM emp;

SELECT EMPNO, ENAME, SAL, COMM FROM emp WHERE SAL BETWEEN 500 AND 3000 AND COMM IS NOT NULL;

#연습 (문제5-EMP)
#사원들 중 이름이 '기'로 끝나기나, '김'이 들어가는 
#사원들의 사번, 이름, 입사일을 조회하되, 
#사번기준 내림차순 정렬하여 조회하는 쿼리문을 작성하세요.

SELECT * FROM emp;

SELECT EMPNO, ENAME, HIREDATE FROM emp WHERE ENAME LIKE '%기' OR ENAME LIKE '%김%' ORDER BY EMPNO DESC;

#연습 (문제6-EMP)
#사원의 사번, 이름, 부서번호, 부서명을 조회해보자. 
#부서명은 부서번호가 10일 때는 '인사부', 
#20일 때는 '영업부, 30일 때는 '개발부, 
#그 외의 값은 '생산부'로 조회되어야 한다. 
#조인 사용하는 문제 아님. CASE 사용.

SELECT EMPNO, ENAME, DEPTNO, CASE DEPTNO WHEN 10 THEN '인사부' WHEN 20 THEN '영업부' WHEN 30 THEN '개발부' ELSE '생산부' END AS DEPT_NAME FROM emp;

#연습 (문제7-EMP)
#1월에 입사한 모든 사원의 사번, 이름, 입사일, 커미션을 
#입사일 기준 오름차순으로 조회하는 쿼리문을 작성하세요. 
#단, 커미션이 NULL일 경우 커미션은 0으로 조회되어야 한다.

SELECT EMPNO, ENAME, HIREDATE, IFNULL(COMM, 0) AS COMM FROM emp WHERE MONTH(HIREDATE) = 1 ORDER BY HIREDATE ASC;

SELECT * FROM emp;