 
 
CREATE TABLE BASIC_BOARD (
BOARD_NUM INT PRIMARY KEY AUTO_INCREMENT  #컬럼의값을지정하지않으면자동으로1씩증가된값을넣어주는기능을한다.
, TITLE VARCHAR(30)
, WRITER VARCHAR(20)
, CONTENT VARCHAR(50)
, READ_CNT INT DEFAULT 0
, CREATE_DATE DATETIME DEFAULT SYSDATE()
);
 
SELECT * FROM BASIC_BOARD;
 
INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT) VALUES ('제목1', '작성자1', '내용1');
INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT) VALUES ('제목2', '작성자2', '내용2');
INSERT INTO BASIC_BOARD (TITLE, WRITER, CONTENT) VALUES ('제목3', '작성자3', '내용3');
COMMIT;

SELECT * FROM BASIC_BOARD;

#데이터에 변화가 생기는 쿼리문(insert)(deletet)(updates)을 실행하면 commit or rollback 실행이지만 스프링은 자동commit


#회원 정보 테이블
CREATE TABLE BASIC_MEMBER (
	MEM_ID VARCHAR(20) PRIMARY KEY,
	MEM_PW VARCHAR(20) NOT NULL,
	MEM_NAME VARCHAR(10),
	MEM_AGE INT,
	BIRTHDAY DATETIME
);

SELECT * FROM BASIC_MEMBER;

SELECT MEM_NAME
FROM BASIC_MEMBER
WHERE MEM_ID = 'javaboy';
