# 외래키 (Foreign Key)
# 테이블 간의 관계 표현에 사용 다른 테이블의 기본키를 참조 함!


DROP TABLE QNA_BOARD;
DROP TABLE REPLY;

# 게시판 테이블
CREATE TABLE QNA_BOARD (
	BOARD_NUM INT PRIMARY KEY
	, TITLE VARCHAR(20)
	, CONTENT VARCHAR(20)
	, WRITER VARCHAR(20)
);

# 댓글 테이블
CREATE TABLE REPLY (
	REPLY_NUM INT PRIMARY KEY
	, REPLY_CONTENT VARCHAR(20)
	, REPLY_WRITER VARCHAR(20)
	, BOARD_NUM INT REFERENCES QNA_BOARD (BOARD_NUM) ON DELETE CASCADE # (글 번호) + 따라붙은 애들도 같이 지워짐
);

INSERT INTO QNA_BOARD () VALUES (1, 'AA', 'AA내용', '김');
INSERT INTO QNA_BOARD () VALUES (2, 'BB', 'BB내용', '이');
INSERT INTO QNA_BOARD () VALUES (3, 'CC', 'CC내용', '박');

INSERT INTO REPLY () VALUES (1, '11', '김', 1);
INSERT INTO REPLY () VALUES (2, '22', '이', 1);
INSERT INTO REPLY () VALUES (3, '33', '김', 2);

DELETE FROM QNA_BOARD
WHERE BOARD_NUM = 1;

SELECT * FROM REPLY;

INSERT INTO REPLY () VALUES (4, '44', '윤', 5);


# 연습용 테이블
# 학급 정보
CREATE TABLE CLASS_INFO (
	CLASS_NUM INT PRIMARY KEY #학급번호
	, CLASS_NAME VARCHAR(20) NOT NULL UNIQUE #학급명
);

# 학생 정보
CREATE TABLE STUDENT_INFO (
	STU_NUM INT PRIMARY KEY AUTO_INCREMENT
	, STU_NAME VARCHAR(20) NOT NULL 
	, STU_AGE INT
	, CLASS_NUM INT REFERENCES CLASS_INFO (CLASS_NUM)
);

INSERT INTO CLASS_INFO () VALUES (1, '루피반');
INSERT INTO CLASS_INFO () VALUES (2, '뽀로로반');
INSERT INTO CLASS_INFO () VALUES (3, '크롱반');

INSERT INTO STUDENT_INFO () VALUES (1, '김루피', 30, 1);
INSERT INTO STUDENT_INFO () VALUES (2, '이루피', 33, 1);
INSERT INTO STUDENT_INFO () VALUES (3, '정루피', 35, 1);

INSERT INTO STUDENT_INFO () VALUES (4, '뽀로롱', 20, 2);
INSERT INTO STUDENT_INFO () VALUES (5, '뽀롱로', 23, 2);
INSERT INTO STUDENT_INFO () VALUES (6, '뽀로리', 25, 2);

INSERT INTO STUDENT_INFO () VALUES (7, '한크롱', 40, 3);
INSERT INTO STUDENT_INFO () VALUES (8, '박크롱', 43, 3);
INSERT INTO STUDENT_INFO () VALUES (9, '윤크롱', 45, 3);

COMMIT;

SELECT * FROM CLASS_INFO;
SELECT * FROM STUDENT_INFO;
